version: '3'
services:
  poc-postgres:
    image: 'postgres:14.5'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=POSTGRES_USER
      - POSTGRES_PASSWORD=POSTGRES_PASSWORD
      - POSTGRES_DB=POSTGRES_DB
